### PR TITLE
aionr-arm32

### PR DESCRIPTION
**Pull request by vito11**
support arm32 platform

### CODE REVIEW

**Comment by r3gata** [comment]
I am interested in the changes you have proposed, as I too was trying to get the kernel to run on the Raspberry Pi 4B (4GB edition). I am using the aarch64-unknown-linux-gnu Rust toolchain to try to compile this natively.

However, I run into these errors when running the build:

error[E0512]: transmute called with types of different sizes
   --> vms/avm/rjni/src/ffi.rs:731:55
    |
731 | pub fn into_raw<T>(handler: i32) -> *mut T { unsafe { mem::transmute(handler) } }
    |                                                       ^^^^^^^^^^^^^^
    |
    = note: source type: i32 (32 bits)
    = note: target type: *mut T (64 bits)

error[E0512]: transmute called with types of different sizes
   --> vms/avm/rjni/src/ffi.rs:734:51
    |
734 | pub fn from_raw<T>(ptr: *mut T) -> i32 { unsafe { mem::transmute(ptr) } }
    |                                                   ^^^^^^^^^^^^^^
    |
    = note: source type: *mut T (64 bits)
    = note: target type: i32 (32 bits)

error[E0512]: transmute called with types of different sizes
   --> vms/avm/rjni/src/ffi.rs:130:43
    |
130 |     pub fn l(&self) -> jobject { unsafe { mem::transmute(self.data as u32) } }
    |                                           ^^^^^^^^^^^^^^
    |
    = note: source type: u32 (32 bits)
    = note: target type: *mut libc::c_void (64 bits)

error[E0512]: transmute called with types of different sizes
   --> vms/avm/rjni/src/lib.rs:657:37
    |
657 |     fn into(self) -> i32 { unsafe { mem::transmute(&self) } }
    |                                     ^^^^^^^^^^^^^^
    |
    = note: source type: &Class<'_> (64 bits)
    = note: target type: i32 (32 bits)

error: aborting due to 4 previous errors

Have you noticed anything similar to this before?

**Comment by vito11** [comment]
> I am interested in the changes you have proposed, as I too was trying to get the kernel to run on the Raspberry Pi 4B (4GB edition).
> I am using the aarch64-unknown-linux-gnu Rust toolchain to try to compile this natively. I have installed Ubuntu Server 18.04 (64 bit) on the Pi as the OS).
> 
> However, I run into these errors when running the build:
> 
> error[E0512]: transmute called with types of different sizes
> --> vms/avm/rjni/src/ffi.rs:731:55
> |
> 731 | pub fn into_raw(handler: i32) -> *mut T { unsafe { mem::transmute(handler) } }
> | ^^^^^^^^^^^^^^
> |
> = note: source type: i32 (32 bits)
> = note: target type: *mut T (64 bits)
> 
> error[E0512]: transmute called with types of different sizes
> --> vms/avm/rjni/src/ffi.rs:734:51
> |
> 734 | pub fn from_raw(ptr: *mut T) -> i32 { unsafe { mem::transmute(ptr) } }
> | ^^^^^^^^^^^^^^
> |
> = note: source type: *mut T (64 bits)
> = note: target type: i32 (32 bits)
> 
> error[E0512]: transmute called with types of different sizes
> --> vms/avm/rjni/src/ffi.rs:130:43
> |
> 130 | pub fn l(&self) -> jobject { unsafe { mem::transmute(self.data as u32) } }
> | ^^^^^^^^^^^^^^
> |
> = note: source type: u32 (32 bits)
> = note: target type: *mut libc::c_void (64 bits)
> 
> error[E0512]: transmute called with types of different sizes
> --> vms/avm/rjni/src/lib.rs:657:37
> |
> 657 | fn into(self) -> i32 { unsafe { mem::transmute(&self) } }
> | ^^^^^^^^^^^^^^
> |
> = note: source type: &Class<'_> (64 bits)
> = note: target type: i32 (32 bits)
> 
> error: aborting due to 4 previous errors
> 
> Have you noticed anything similar to this before? Is it the OS? Or the toolchain?

I was trying to install aionr on raspbian which is 32bit, so I did these changes to corrent the compile error, but I failed to sync some blocks on amity(testnet). After I dive deep into the rjni code, I found that its not easy to compate with the 32bit libjvm.so which aionr relys on. 

And now I am aslo trying to install aionr on arm64 Pi (ubuntu 18.04, same as you),  you can use the official branch and ignore this PR.   But there are also sime issues to be fixed:
1.  A link error related to /util/crypto/src/util_helpers.c  , you can add the following code to support arm64.
```#ifdef __aarch64__
uint32_t rust_crypto_util_fixed_time_eq_asm(uint8_t* lhsp, uint8_t* rhsp, size_t count) {
    if (count == 0) {
        return 1;
    }
    uint8_t result = 0;
    asm(
        " \
            1: \
            \
            ldrb w4, [%1]; \
            ldrb w5, [%2]; \
            eor w4, w4, w5; \
            orr %w0, %w0, w4; \
            \
            add %1, %1, #1; \
            add %2, %2, #1; \
            subs %w3, %w3, #1; \
            bne 1b; \
        "
        : "+&r" (result), "+&r" (lhsp), "+&r" (rhsp), "+&r" (count) // all input and output
        : // input
        : "w4", "w5", "cc" // clobbers
    );
    
    return result;
}
#endif```
2.  FastVM seems only support x86_64, I am still working on this issue to sync with FVM blocks, I will let you know if I finished this.

**Comment by r3gata** [comment]
Vito, thank you so much for the quick update! I really appreciate the detailed response, and the update on your progress. I was about to dig up another microsd card so I could try out the armhf (32-bit) build of Ubuntu 18.04 on my RPi4 as well, but it sounds like that will yield the same results.

I am definitely not as versed in Rust as I am other languages, so I was getting nowhere fast looking at it myself.

So just to be clear, right now your current build state is:
1. Ubuntu 18.04 (64-bit, arm64)
2. x86_64-unknown-linux-gnu as the Rust toolchain
3. Using the current master branch
4. The change you mentioned above to the util_helpers.c file
5. Working on the FastVM implementation to play nice with arm64

Is that correct?

I will be more than happy to test things out, whenever you have any updates to share!

**Comment by vito11** [comment]
Yes, My build environment is just the same as you mentioned.
Please notice that, if this FVM issue not being fixed, the sync will always stop at the every FVM block.  I am not sure if I can make it to support arm64, I have talked to one team developer, seems not so easy to implement.

But, there is another way to workaround, since FVM is the old contract VM (We have AVM), maybe new blocks will never contain any FVM transactions on mainnet, you can download all block db from another healthy node to bypass the sync process.

**Comment by r3gata** [comment]
I am indeed building on the Pi (just easier for me in the long run). By host default toolchain, do you mean the x86_64-unknown-linux-gnu (as per the aionr instructions) or the aarch64-unknown-linux-gnu (the one I believe would native compile for the Pi to be able to run it)?

**Comment by vito11** [comment]
should be aarch64-unknown-linux-gnu，just don‘t specific，rust will use host
default toolchain.

r3gata <notifications@github.com>于2019年11月22日 周五下午11:13写道：

**Comment by vito11** [comment]
> I am indeed building on the Pi (just easier for me in the long run). By host default toolchain, do you mean the x86_64-unknown-linux-gnu (as per the aionr instructions) or the aarch64-unknown-linux-gnu (the one I believe would native compile for the Pi to be able to run it)?

Hi, I have finally successed to make fastvm run on aarch64, pls check my fork https://github.com/aionnetwork/aionr

**Pull request closed without merging**
